name: Ardal_Plugin
version: '${project.version}'
main: org.ardal.Ardal
api-version: '1.16'
depend: [Citizens]
commands:
  quest:
    description: Manage quests.
    permission: ardal_plugin.quest
  ardal:
    description: Manager player info
    permission: ardal_plugin.ardal
  custom_npc:
    description: Manager npc.
    permission: ardal_plugin.npc
  ec:
    description: Open enderchest.
    permission: ardal_plugin.ec
  story:
    description: Open your adventure story.
    permission: ardal_plugin.story
  adventureLevel:
    description: your adventure level.
    permission: ardal_plugin.adventureLevel
